package com.mcmiddleearth.entities.ai.goal;

public enum GoalType {
    HOLD_POSITION,
    ATTACK_ENTITY,
    ATTACK_ENTITY_FLYING,
    DEFEND_ENTITY,
    WATCH_ENTITY,
    RANGED_ATTACK_ENTITY,
    FOLLOW_ENTITY,
    ATTACK_CLOSE,
//    DIG,
//    WALK,
//    FLY,
    FOLLOW_CHECKPOINTS,
//    FOLLOW_CHECKPOINTS_WINGED,
    RANDOM_CHECKPOINTS,
    GOTO_LOCATION,
    MIMIC,
    JOCKEY,
    NONE;
}
